#!/usr/bin/env python3
"""Build map/provinces.png, data/provinces.csv and data/countries.json from Natural Earth admin-1 regions.

Source: ne_10m_admin_1_states_provinces (public domain, https://www.naturalearthdata.com).
Every state/province becomes one game province owned by its country (adm0_a3 tag).

The map is equirectangular: longitude -180..180 across the width, latitude MAP_TOP..MAP_BOTTOM
down the height (fitted against the land mask in map/rivers.png). Provinces are snapped to the
game's own coastline: land pixels outside every polygon join the nearest province, and pixels
the game shows as sea belong to the single ocean province.

This regenerates the three data files from scratch, so province ids change only if the source
data changes. Hand edits to them are overwritten.

Usage: python3 tools/import_natural_earth.py path/to/ne_10m_admin_1_states_provinces.zip   (or the .shp)
       (needs: pip install pyshp pillow numpy scipy)
"""
import argparse
import colorsys
import hashlib
import json
import pathlib
import sys
import zlib

import numpy as np
import shapefile
from PIL import Image, ImageDraw
from scipy.ndimage import distance_transform_edt, gaussian_filter

ROOT = pathlib.Path(__file__).resolve().parent.parent
PROVINCES_PNG = ROOT / "map" / "provinces.png"
RIVERS_PNG = ROOT / "map" / "rivers.png"
HEIGHTMAP_PNG = ROOT / "map" / "heightmapps.png"
PROVINCES_CSV = ROOT / "data" / "provinces.csv"
COUNTRIES_JSON = ROOT / "data" / "countries.json"

WIDTH, HEIGHT = 5632, 2316
MAP_TOP, MAP_BOTTOM = 86.6, -61.6    # latitude of the top and bottom image edges
MIN_PROVINCE_PX = 20                 # smaller regions merge into a same-country neighbour
OCEAN_ID, OCEAN_COLOR = 1, (0, 0, 0)
SEA_LEVEL = 128                      # heightmap value of sea level

CSV_HEADER = """# Province definitions. One row per colour painted in map/provinces.png.
# id;color;name;terrain;owner
# - id:      positive integer, unique. Used everywhere in game logic and saves, so never renumber.
# - color:   hex RGB of the province in map/provinces.png, unique.
# - terrain: free-form for now (plains, hills, mountains, sea, ...). "sea" marks water provinces.
# - owner:   country tag from data/countries.json, or empty for unowned.
# Generated by tools/import_natural_earth.py from Natural Earth admin-1 (public domain).
# tools/sync_provinces.py appends a row for every colour in the map that is not listed here.
id;color;name;terrain;owner
"""


def land_mask():
    """Game land/sea mask, classified exactly like tools/bake_map_fields.py."""
    rivers = np.asarray(Image.open(RIVERS_PNG).convert("RGB")).astype(np.int16)
    spread = rivers.max(axis=-1) - rivers.min(axis=-1)
    river = spread > 60
    sea = (~river) & (rivers.max(axis=-1) < 190)
    return ~sea


def rasterize(reader):
    """Draw every region with fill = its record index + 1 (0 = no region)."""
    canvas = Image.new("I", (WIDTH, HEIGHT), 0)
    draw = ImageDraw.Draw(canvas)
    sx = WIDTH / 360.0
    sy = HEIGHT / (MAP_TOP - MAP_BOTTOM)
    for index, shape in enumerate(reader.iterShapes()):
        points = np.asarray(shape.points)
        if len(points) == 0:
            continue
        xs = (points[:, 0] + 180.0) * sx
        ys = (MAP_TOP - points[:, 1]) * sy
        parts = list(shape.parts) + [len(points)]
        for a, b in zip(parts[:-1], parts[1:]):
            if b - a >= 3:
                draw.polygon(list(zip(xs[a:b], ys[a:b])), fill=index + 1)
    return np.asarray(canvas, dtype=np.int32)


def fill_from_nearest(regions, land):
    """Give unassigned land pixels the region of the nearest assigned pixel (east-west wraps)."""
    pad = 64
    padded = np.pad(regions, ((0, 0), (pad, pad)), mode="wrap")
    _, (iy, ix) = distance_transform_edt(padded == 0, return_indices=True)
    nearest = padded[iy, ix][:, pad:-pad]
    out = np.where(land, np.where(regions > 0, regions, nearest), 0)
    return out


def merge_small(regions, tags, min_px):
    """Merge regions under min_px into the same-country neighbour they share the longest border with.

    Repeats until nothing changes. Regions with no same-country neighbour (small islands,
    microstates) stay as they are. Returns the relabelled array.
    """
    n = len(tags)
    tag_ids = np.unique(tags, return_inverse=True)[1]
    while True:
        counts = np.bincount(regions.ravel(), minlength=n)
        # border lengths between 4-connected neighbours (east-west wraps)
        a = np.concatenate([regions.ravel(), regions[:-1].ravel()])
        b = np.concatenate([np.roll(regions, -1, axis=1).ravel(), regions[1:].ravel()])
        keep = (a != b) & (a > 0) & (b > 0)
        a, b = a[keep], b[keep]
        a, b = np.concatenate([a, b]), np.concatenate([b, a])
        same = tag_ids[a] == tag_ids[b]
        small = (counts[a] > 0) & (counts[a] < min_px)
        a, b = a[same & small], b[same & small]
        if a.size == 0:
            return regions
        pairs, border = np.unique(a.astype(np.int64) * n + b, return_counts=True)
        src, dst = pairs // n, pairs % n
        target = np.arange(n)
        best = {}
        for s_, d_, l_ in zip(src, dst, border):
            # longest shared border wins; ties go to the larger neighbour
            score = (l_, counts[d_])
            if s_ not in best or score > best[s_][0]:
                best[s_] = (score, d_)
        for s_, (_, d_) in best.items():
            if target[d_] != s_:       # avoid swapping two small regions into each other
                target[s_] = d_
        regions = target[regions]


def color_for(key, used):
    """Stable, unique, non-reserved RGB for a province key."""
    salt = 0
    while True:
        value = zlib.crc32(f"{key}:{salt}".encode()) & 0xFFFFFF
        rgb = (value >> 16 & 255, value >> 8 & 255, value & 255)
        if rgb not in used and rgb not in (OCEAN_COLOR, (255, 255, 255)):
            used.add(rgb)
            return rgb
        salt += 1


def country_color(tag):
    """Muted, distinct political-map colour derived from the tag."""
    h = int(hashlib.md5(tag.encode()).hexdigest()[:8], 16)
    hue = (h % 360) / 360.0
    sat = 0.45 + (h >> 9) % 30 / 100.0
    val = 0.62 + (h >> 17) % 25 / 100.0
    r, g, b = colorsys.hsv_to_rgb(hue, sat, val)
    return "#%02x%02x%02x" % (round(r * 255), round(g * 255), round(b * 255))


def slope_map(heights):
    """Local slope of the smoothed heightmap; sea is clamped to sea level so coasts don't read as cliffs."""
    h = gaussian_filter(np.maximum(heights.astype(np.float32), SEA_LEVEL), 2.0, mode="wrap")
    return np.hypot(np.roll(h, -1, axis=1) - np.roll(h, 1, axis=1),
                    np.roll(h, -1, axis=0) - np.roll(h, 1, axis=0))


def terrain_for(heights, slopes):
    """Rough placeholder classification from median ruggedness and elevation.

    Calibrated on a handful of known regions (Kansas/Illinois plains, Bavaria hills, Bern/Tirol/Tibet
    mountains). Small provinces beside big ranges can come out too rugged; fix those by hand.
    """
    land = heights > SEA_LEVEL
    if not land.any():
        return "plains"
    slope, elev = np.median(slopes[land]), np.median(heights[land])
    if slope >= 4.5 or elev >= 204 or (elev >= 185 and slope >= 3.5):
        return "mountains"
    if slope >= 2.0 or elev >= 180:
        return "hills"
    return "plains"


def clean(text):
    return " ".join(str(text or "").replace(";", ",").split())


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("shapefile", help="ne_10m_admin_1_states_provinces .zip or .shp")
    args = parser.parse_args()

    Image.MAX_IMAGE_PIXELS = None
    reader = shapefile.Reader(args.shapefile, encoding="utf-8")
    records = reader.records()
    land = land_mask()

    regions = fill_from_nearest(rasterize(reader), land)
    tags = np.array([""] + [clean(r["adm0_a3"]).upper() for r in records])
    regions = merge_small(regions, tags, MIN_PROVINCE_PX)
    counts = np.bincount(regions.ravel(), minlength=len(records) + 1)
    heights = np.asarray(Image.open(HEIGHTMAP_PNG).convert("RGB"))[..., 0]
    slopes = slope_map(heights).ravel()

    # region index -> province id, in source order; regions that ended up with no pixels are dropped
    province_of = np.zeros(len(records) + 1, dtype=np.int32)
    rows, used_colors, owners = [], {OCEAN_COLOR}, {}
    order = np.argsort(regions.ravel(), kind="stable")
    starts = np.concatenate([[0], np.cumsum(counts)])
    next_id = OCEAN_ID + 1
    for index, rec in enumerate(records, start=1):
        if counts[index] == 0:
            continue
        tag = clean(rec["adm0_a3"]).upper()
        name = clean(rec["name"]) or clean(rec["name_en"]) or f"{clean(rec['admin'])} {next_id}"
        pixels = order[starts[index]:starts[index + 1]]
        rgb = color_for(rec["adm1_code"] or index, used_colors)
        rows.append((next_id, rgb, name, terrain_for(heights.ravel()[pixels], slopes[pixels]), tag))
        owners.setdefault(tag, clean(rec["admin"]))
        province_of[index] = next_id
        next_id += 1

    palette = np.zeros((next_id, 3), dtype=np.uint8)
    palette[OCEAN_ID] = OCEAN_COLOR
    for pid, rgb, *_ in rows:
        palette[pid] = rgb
    ids = province_of[regions]
    ids[ids == 0] = OCEAN_ID
    Image.fromarray(palette[ids], "RGB").save(PROVINCES_PNG, optimize=True)

    with PROVINCES_CSV.open("w", encoding="utf-8", newline="\n") as f:
        f.write(CSV_HEADER)
        f.write(f"{OCEAN_ID};#{'%02x%02x%02x' % OCEAN_COLOR};Ocean;sea;\n")
        for pid, rgb, name, terrain, tag in rows:
            f.write(f"{pid};#{'%02x%02x%02x' % rgb};{name};{terrain};{tag}\n")

    countries = [{"tag": t, "name": n, "color": country_color(t)} for t, n in sorted(owners.items())]
    with COUNTRIES_JSON.open("w", encoding="utf-8", newline="\n") as f:
        f.write("[\n" + ",\n".join("\t" + json.dumps(c, ensure_ascii=False) for c in countries) + "\n]\n")

    sizes = counts[1:][counts[1:] > 0]
    print(f"{len(rows)} provinces in {len(countries)} countries "
          f"({len(records) - len(rows)} source regions were off-map, sub-pixel or merged into a neighbour)")
    print(f"province size (px): min {sizes.min()}, median {int(np.median(sizes))}, max {sizes.max()}; "
          f"{int((sizes < MIN_PROVINCE_PX).sum())} under {MIN_PROVINCE_PX} px (islands and microstates)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
