#!/usr/bin/env python3
"""Build the world map's provinces, lakes and rivers from Natural Earth (public domain).

Inputs (the .zip downloads from https://www.naturalearthdata.com, or the .shp inside):
  admin-1   ne_10m_admin_1_states_provinces    -> one province per state/province, owned by its country
  lakes     ne_10m_lakes                        -> lakes; big ones become lake provinces
  rivers    ne_10m_rivers_lake_centerlines      -> rivers drawn in 4 width classes; river crossings and
                                                   navigable links in data/adjacencies.csv

Outputs (all regenerated; hand edits are overwritten):
  map/rivers.png, map/heightmapps.png (G/B fields via bake_map_fields.py), map/provinces.png,
  data/provinces.csv, data/countries.json, data/adjacencies.csv

The coastline comes from tools/data/ocean_mask.png. Provinces snap to it: land pixels outside every
polygon join the nearest province and sea pixels belong to the single Ocean province. Lakes of at
least LAKE_MIN_PX become lake provinces; smaller lakes are drawn as water but belong to the land
province around them.

Usage: python3 tools/import_natural_earth.py ADMIN1.zip LAKES.zip RIVERS.zip
       (needs: pip install pyshp pillow numpy scipy)
"""
import argparse
import colorsys
import hashlib
import json
import sys
import zlib

import numpy as np
import shapefile
from PIL import Image
from scipy.ndimage import distance_transform_edt, gaussian_filter

import bake_map_fields
import ne_adjacency
import ne_water
from map_common import (PROVINCES_PNG, ROOT, SEA_LEVEL, clean, load_heights, rasterize_polygons)

PROVINCES_CSV = ROOT / "data" / "provinces.csv"
COUNTRIES_JSON = ROOT / "data" / "countries.json"
ADJACENCIES_CSV = ROOT / "data" / "adjacencies.csv"

MIN_PROVINCE_PX = 20                 # smaller regions merge into a same-country neighbour
LAKE_MIN_PX = 150                    # smaller lakes stay part of the surrounding land province
OCEAN_ID, OCEAN_COLOR = 1, (0, 0, 0)

CSV_HEADER = """# Province definitions. One row per colour painted in map/provinces.png.
# id;color;name;terrain;owner
# - id:      positive integer, unique. Used everywhere in game logic and saves, so never renumber.
# - color:   hex RGB of the province in map/provinces.png, unique.
# - terrain: plains, hills, mountains, sea or lake. "sea" and "lake" are water provinces.
# - owner:   country tag from data/countries.json, or empty for unowned.
# Generated by tools/import_natural_earth.py from Natural Earth (public domain).
id;color;name;terrain;owner
"""

ADJ_HEADER = """# Province adjacency. Generated by tools/import_natural_earth.py; one row per pair, a < b.
# a;b;border;crossing;navigable
# - border:    shared border length in map pixels (0 = linked only by a navigable river mouth)
# - crossing:  river running along this border; armies attacking across it are penalised
# - navigable: navigable river connecting the two provinces; small ships can sail between them
a;b;border;crossing;navigable
"""


def fill_from_nearest(regions, land):
    """Give unassigned land pixels the region of the nearest assigned pixel (east-west wraps)."""
    pad = 64
    padded = np.pad(regions, ((0, 0), (pad, pad)), mode="wrap")
    _, (iy, ix) = distance_transform_edt(padded == 0, return_indices=True)
    nearest = padded[iy, ix][:, pad:-pad]
    out = np.where(land, np.where(regions > 0, regions, nearest), 0)
    return out


def merge_small(regions, tags, min_px):
    """Merge regions under min_px into the same-country neighbour they share the longest border with.

    Repeats until nothing changes. Regions with no same-country neighbour (small islands,
    microstates) stay as they are. Returns the relabelled array.
    """
    n = len(tags)
    tag_ids = np.unique(tags, return_inverse=True)[1]
    while True:
        counts = np.bincount(regions.ravel(), minlength=n)
        # border lengths between 4-connected neighbours (east-west wraps)
        a = np.concatenate([regions.ravel(), regions[:-1].ravel()])
        b = np.concatenate([np.roll(regions, -1, axis=1).ravel(), regions[1:].ravel()])
        keep = (a != b) & (a > 0) & (b > 0)
        a, b = a[keep], b[keep]
        a, b = np.concatenate([a, b]), np.concatenate([b, a])
        same = tag_ids[a] == tag_ids[b]
        small = (counts[a] > 0) & (counts[a] < min_px)
        a, b = a[same & small], b[same & small]
        if a.size == 0:
            return regions
        pairs, border = np.unique(a.astype(np.int64) * n + b, return_counts=True)
        src, dst = pairs // n, pairs % n
        target = np.arange(n)
        best = {}
        for s_, d_, l_ in zip(src, dst, border):
            # longest shared border wins; ties go to the larger neighbour
            score = (l_, counts[d_])
            if s_ not in best or score > best[s_][0]:
                best[s_] = (score, d_)
        for s_, (_, d_) in best.items():
            if target[d_] != s_:       # avoid swapping two small regions into each other
                target[s_] = d_
        regions = target[regions]


def color_for(key, used):
    """Stable, unique, non-reserved RGB for a province key."""
    salt = 0
    while True:
        value = zlib.crc32(f"{key}:{salt}".encode()) & 0xFFFFFF
        rgb = (value >> 16 & 255, value >> 8 & 255, value & 255)
        if rgb not in used and rgb not in (OCEAN_COLOR, (255, 255, 255)):
            used.add(rgb)
            return rgb
        salt += 1


def country_color(tag):
    """Muted, distinct political-map colour derived from the tag."""
    h = int(hashlib.md5(tag.encode()).hexdigest()[:8], 16)
    hue = (h % 360) / 360.0
    sat = 0.45 + (h >> 9) % 30 / 100.0
    val = 0.62 + (h >> 17) % 25 / 100.0
    r, g, b = colorsys.hsv_to_rgb(hue, sat, val)
    return "#%02x%02x%02x" % (round(r * 255), round(g * 255), round(b * 255))


def slope_map(heights):
    """Local slope of the smoothed heightmap; sea is clamped to sea level so coasts don't read as cliffs."""
    h = gaussian_filter(np.maximum(heights.astype(np.float32), SEA_LEVEL), 2.0, mode="wrap")
    return np.hypot(np.roll(h, -1, axis=1) - np.roll(h, 1, axis=1),
                    np.roll(h, -1, axis=0) - np.roll(h, 1, axis=0))


def terrain_for(heights, slopes):
    """Rough placeholder classification from median ruggedness and elevation.

    Calibrated on a handful of known regions (Kansas/Illinois plains, Bavaria hills, Bern/Tirol/Tibet
    mountains). Small provinces beside big ranges can come out too rugged; fix those by hand.
    """
    land = heights > SEA_LEVEL
    if not land.any():
        return "plains"
    slope, elev = np.median(slopes[land]), np.median(heights[land])
    if slope >= 4.5 or elev >= 204 or (elev >= 185 and slope >= 3.5):
        return "mountains"
    if slope >= 2.0 or elev >= 180:
        return "hills"
    return "plains"


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("admin1", help="ne_10m_admin_1_states_provinces .zip or .shp")
    parser.add_argument("lakes", help="ne_10m_lakes .zip or .shp")
    parser.add_argument("rivers", help="ne_10m_rivers_lake_centerlines .zip or .shp")
    args = parser.parse_args()

    water = ne_water.build(args.lakes, args.rivers)
    bake_map_fields.main(water.river_lines)
    heights = load_heights()
    slopes = slope_map(heights).ravel()

    # lakes: tiny pieces join the lake they touch; lakes still under LAKE_MIN_PX stay land provinces
    lake_regions = np.where(water.water, water.lake_index, 0)
    lake_regions = merge_small(lake_regions, np.array([""] + ["LAKE"] * len(water.lake_names)), LAKE_MIN_PX)
    lake_counts = np.bincount(lake_regions.ravel(), minlength=len(water.lake_names) + 1)
    big_lake = (lake_regions > 0) & (lake_counts[lake_regions] >= LAKE_MIN_PX)
    land = ~(water.ocean | big_lake)

    reader = shapefile.Reader(args.admin1, encoding="utf-8")
    records = reader.records()
    regions = rasterize_polygons(reader.iterShapes(), range(1, len(records) + 1))
    regions = fill_from_nearest(regions, land)
    tags = np.array([""] + [clean(r["adm0_a3"]).upper() for r in records])
    regions = merge_small(regions, tags, MIN_PROVINCE_PX)
    counts = np.bincount(regions.ravel(), minlength=len(records) + 1)

    ids = np.full(regions.shape, OCEAN_ID, dtype=np.int32)
    rows, used_colors, owners = [], {OCEAN_COLOR}, {}
    next_id = OCEAN_ID + 1

    def add(key, name, terrain, tag):
        nonlocal next_id
        rgb = color_for(key, used_colors)
        rows.append((next_id, rgb, name, terrain, tag))
        next_id += 1
        return next_id - 1

    # land provinces in source order; regions that ended up with no pixels are dropped
    province_of = np.zeros(len(records) + 1, dtype=np.int32)
    order = np.argsort(regions.ravel(), kind="stable")
    starts = np.concatenate([[0], np.cumsum(counts)])
    for index, rec in enumerate(records, start=1):
        if counts[index] == 0:
            continue
        tag = clean(rec["adm0_a3"]).upper()
        name = clean(rec["name"]) or clean(rec["name_en"]) or f"{clean(rec['admin'])} {next_id}"
        pixels = order[starts[index]:starts[index + 1]]
        terrain = terrain_for(heights.ravel()[pixels], slopes[pixels])
        province_of[index] = add(rec["adm1_code"] or index, name, terrain, tag)
        owners.setdefault(tag, clean(rec["admin"]))
    ids[regions > 0] = province_of[regions[regions > 0]]

    # lake provinces
    lake_count = 0
    for index in np.nonzero(lake_counts >= LAKE_MIN_PX)[0]:
        if index == 0:
            continue
        name = water.lake_names[index - 1] or f"Lake {next_id}"
        ids[big_lake & (lake_regions == index)] = add(f"lake:{name}:{index}", name, "lake", "")
        lake_count += 1

    palette = np.zeros((next_id, 3), dtype=np.uint8)
    palette[OCEAN_ID] = OCEAN_COLOR
    for pid, rgb, *_ in rows:
        palette[pid] = rgb
    Image.fromarray(palette[ids], "RGB").save(PROVINCES_PNG, optimize=True)

    with PROVINCES_CSV.open("w", encoding="utf-8", newline="\n") as f:
        f.write(CSV_HEADER)
        f.write(f"{OCEAN_ID};#{'%02x%02x%02x' % OCEAN_COLOR};Ocean;sea;\n")
        for pid, rgb, name, terrain, tag in rows:
            f.write(f"{pid};#{'%02x%02x%02x' % rgb};{name};{terrain};{tag}\n")

    countries = [{"tag": t, "name": n, "color": country_color(t)} for t, n in sorted(owners.items())]
    with COUNTRIES_JSON.open("w", encoding="utf-8", newline="\n") as f:
        f.write("[\n" + ",\n".join("\t" + json.dumps(c, ensure_ascii=False) for c in countries) + "\n]\n")

    is_water = np.zeros(next_id, dtype=bool)
    is_water[OCEAN_ID] = True
    for pid, _, _, terrain, _ in rows:
        is_water[pid] = terrain == "lake"
    adjacency = ne_adjacency.compute(ids, is_water, water.river_index, water.rivers)
    with ADJACENCIES_CSV.open("w", encoding="utf-8", newline="\n") as f:
        f.write(ADJ_HEADER)
        for a, b, border, crossing, nav in adjacency:
            f.write(f"{a};{b};{border};{crossing};{nav}\n")

    land_rows = len(rows) - lake_count
    sizes = counts[1:][counts[1:] > 0]
    print(f"{land_rows} land provinces in {len(countries)} countries, {lake_count} lake provinces "
          f"({len(records) - land_rows} admin-1 regions were off-map, sub-pixel or merged)")
    print(f"province size (px): min {sizes.min()}, median {int(np.median(sizes))}, max {sizes.max()}; "
          f"{int((sizes < MIN_PROVINCE_PX).sum())} under {MIN_PROVINCE_PX} px (islands and microstates)")
    print(f"{len(adjacency)} adjacencies: {sum(1 for r in adjacency if r[3])} river crossings, "
          f"{sum(1 for r in adjacency if r[4])} navigable river links")
    return 0


if __name__ == "__main__":
    sys.exit(main())
